### PR TITLE
Implemented latex parsing feature

### PR DESCRIPTION
**Pull request by WillbsoluteVodka**
One existing bug:
When pasting latex expression from elsewhere, the parsing leaves an additional $ before the expression.

Screenshot 2023-09-12 at 10 09 55 PM

### CODE REVIEW

**Comment by forrestbao** [comment]
Thanks for the PR. Has the pasting bug been reported by other remirror users?

**Comment by forrestbao** [comment]
There are conflicts with Jimmy's PR that I just merged. Can you manually solve the conflicts? @WillbsoluteVodka

**Comment by WillbsoluteVodka** [comment]
i will look into the conflicts and about the latex bugs

**Comment by WillbsoluteVodka** [comment]
I think this branch is ready for merge now!

**Pull request merged**
