### PR TITLE
add pod functionality

### PR DESCRIPTION
**Pull request by chimmyten**
The goal of this PR is to add functionality to the rich nodes. This includes dragging the pods around with the drag handle and the ability to delete pods.

### CODE REVIEW

**Comment by chimmyten** [comment]
render-pods-toolbar

**Comment by forrestbao** [comment]
We don't need edges.

**Comment by chimmyten** [comment]
Okay, just dragging and deleting pods then.

**Comment by forrestbao** [comment]
Yes. And for the dragging part, can you implement dragging without using a handle? E.g., use click(anywhere in the pod)-and-hold to move a pod. I think CodePod implemented this at some point.

**Comment by chimmyten** [comment]
Sure, I'll do that.

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/92ff5e06-1ccc-487f-8f28-cbe678a9f0b3

The nodes are draggable, but to do this I had to set the nodesDraggable property in the Reactflow element to true, which was the fix for the initial "editable pods" issue in #1. Here's a link with someone else who was having the same issue: https://github.com/wbkd/react-flow/discussions/2694. I'll work on fixing this issue. 

Additionally, I found out that the pods behave differently when I screen record (I can select multiple pods and move them at the same time which does not happen when using the app normally). I'll look at the setFocusedEditor function in Codepod to see if implementing something similar might fix this.

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/26d04082-b128-4939-a44d-099c43a96b1e

The pods can be dragged after an initial click, will work on getting around the "nodrag" issue but I'm not sure how Codepod worked around it.

**Comment by forrestbao** [comment]
Why requiring an initial click to drag the box? How this behavior: 
1. Click and hold: drag
2. click only: edit

**Comment by chimmyten** [comment]
Yeah that's the issue I'm working on. Right now the "nodrag" class needs to be present on the node before clicking to avoid the issue I described in #1, which prevents the desired behavior. I need to figure out how to get around this.

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/a8071922-cbdc-4b7b-a1b5-c4ad2a524168

I fixed the issue by adding the HotKeyControl component and overlay box from CodePod. To be honest, I don't know why the overlay box is necessary and how it works with HotKeyControl, but if anyone can figure that out that would be great.

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/d80d70ca-569b-42f7-b2f2-0eb843d97a12

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/77aa095d-7e8a-45be-b393-5a94ec06a9b3

Note: pods have to be unfocused for them to be draggable.

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/39a84a28-643e-4ca6-8d5f-6f3d2d867ed6

**Comment by forrestbao** [comment]
@chimmyten good job. Maybe it's time to start working on saving the pod to a JSON file that is compatible with Jupyter format?

**Comment by chimmyten** [comment]
Sounds good, I'll start working on that. Also, this PR is ready for review/merging.

**Comment by chimmyten** [comment]
Merging conflicts should be resolved. This pr is ready to be reviewed and merged.

**Comment by forrestbao** [comment]
In the future, please be specific on the PR. "Add pod functionality" is too general.

**Comment by chimmyten** [comment]
Got it, I'll do that in the future. If you want, you could merge the save as JSON pr and close this one, because I already merged all the changes into that pr anyway.

**Comment by forrestbao** [comment]
Thanks. 
There is a small, dependency-related bug. I check in the main branch. if needed, I will fix from there.

**Pull request merged**
