### PR TITLE
implement remirror editors as reactflow nodes

### PR DESCRIPTION
**Pull request by chimmyten**
As of now, the editors can only be hardcoded onto the canvas. There is also an issue where on first load, the pods can be selected but are not editable. They become editable after seemingly random actions, such as right clicking, opening and closing dev tools, or switching windows on my device. It might have something to do with how React Flow handles selecting pods but I'm not sure. Any input would be appreciated.

### CODE REVIEW

**Comment by forrestbao** [comment]
Thanks @chimmyten. It would be great if you can add a screenshot in each commit.

**Comment by forrestbao** [comment]
And can you document the steps to fire up the app?

**Comment by chimmyten** [comment]
Sure, I've added the steps to the README file.steps-to-start

**Comment by chimmyten** [comment]
> Thanks @chimmyten. It would be great if you can add a screenshot in each commit.

Would I do this by creating a draft pr when I'm working on something? I'm unsure how to add a screenshot for each commit, unless you meant a screenshot for each pr instead.

**Comment by forrestbao** [comment]
> > Thanks @chimmyten. It would be great if you can add a screenshot in each commit.
> 
> Would I do this by creating a draft pr when I'm working on something? I'm unsure how to add a screenshot for each commit, unless you meant a screenshot for each pr instead.

You can add [WIP] in the title of a work-in-progress PR. And you can always  update or post new screenshot in the PR thread.

**Comment by chimmyten** [comment]
Got it, I'll do that in the future. Here's a video for how it looks right now. 


https://github.com/JupyPod/JupyPod/assets/105993789/4518751c-c262-4f2f-9887-de3c428205c2

**Comment by forrestbao** [comment]
Good progress @chimmyten. Keep us posted.

**Comment by chimmyten** [comment]
The pods are now editable when the page first loads. 

https://github.com/JupyPod/JupyPod/assets/105993789/339b1466-33af-4996-aa64-292cdaec5a72

**Pull request merged**
