### PR TITLE
Save as json 

### PR DESCRIPTION
**Pull request by chimmyten**
This pr is for saving the canvas as a Jupyter scheme JSON string. 

Note: I already merged podFunctionality branch into this one because I needed it to implement this feature.

### CODE REVIEW

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/866ddca1-bcaa-4f2b-937c-dd8ac91e0678

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/bed0f600-a50b-4922-8f13-b47245c1e49c

**Comment by chimmyten** [comment]
https://github.com/JupyPod/JupyPod/assets/105993789/c1c02b46-ee6a-4d96-a5ad-5c7ac0272326

**Comment by chimmyten** [comment]
Ready for review

**Comment by forrestbao** [comment]
Where is the JSON file? Can a user select to which file a canvas is saved?  Can the user also import a note from a JSON file?

**Pull request merged**
